({
	"ADD_FILTER_PLUS" : "<b>+</b>",
	"FILTEING_FIELD" : "Поле фильтрации",
	"SIMPLE_FIELD" : "Введите значение фильтра",
	"RANGE_MIN_FIELD" : "От:",
	"RANGE_MAX_FIELD" : "До:",
	"ADD" : "Добавить",
    "ADD_FILTER" : "Добавить фильтр",
	"ADD_MORE" : "Добавить еще",
	"CANCEL" : "Отменить",
	"INPUT_PLACEHOLDER": "Введите значение",
	"FILTERING" : "Фильтровать",
	"REMOVE_OLD" : "Оставить только новый фильтр этого типа",
	"DECLUDING_FILTER" : "Исключающий фильтр",
    "EXCLUDING" : "Исключающий",
	"CLOSE" : "Закрыть",
    "EDIT" : "Изменить",
    "OK" : "Ок",
    "INFO_MSG" : "Выберите поле фильтра.",
    "EDIT_FILTER" : "Редактирование фильтра"
})